#!/usr/bin/env bash
# Regenerates Sources/DL4STensorboard/Autogenerated from the TensorFlow proto definitions.
#
# Requires protoc and protoc-gen-swift, for example from nix:
#   nix-shell -p protobuf protoc-gen-swift --run util/generate-protos.sh
#
# The generated code must not be newer than the SwiftProtobuf runtime version in Package.swift.
set -euo pipefail

TENSORFLOW_TAG="v2.21.0"
# summary.proto imports the histogram definition from the XLA repository, which TensorFlow vendors.
XLA_COMMIT="fbbe95102bc6d041d35910b7cf2e0449950612e5"

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUTPUT="$ROOT/Sources/DL4STensorboard/Autogenerated"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

TENSORFLOW_PROTOS=(
    tensorflow/core/util/event.proto
    tensorflow/core/framework/summary.proto
    tensorflow/core/framework/tensor.proto
    tensorflow/core/framework/tensor_shape.proto
    tensorflow/core/framework/types.proto
    tensorflow/core/framework/resource_handle.proto
)
XLA_PROTOS=(
    xla/tsl/protobuf/histogram.proto
)

cd "$WORK"
for proto in "${TENSORFLOW_PROTOS[@]}"; do
    mkdir -p "$(dirname "$proto")"
    curl -sSfL -o "$proto" "https://raw.githubusercontent.com/tensorflow/tensorflow/$TENSORFLOW_TAG/$proto"
done
for proto in "${XLA_PROTOS[@]}"; do
    mkdir -p "$(dirname "$proto")"
    curl -sSfL -o "$proto" "https://raw.githubusercontent.com/openxla/xla/$XLA_COMMIT/$proto"
done

rm -f "$OUTPUT"/*.pb.swift
protoc --swift_out="$OUTPUT" --swift_opt=Visibility=Internal --swift_opt=FileNaming=DropPath \
    "${TENSORFLOW_PROTOS[@]}" "${XLA_PROTOS[@]}"
