#if !canImport(ObjectiveC)
import XCTest

extension DL4S_TensorboardTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DL4S_TensorboardTests = [
        ("testWriter", testWriter),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DL4S_TensorboardTests.__allTests__DL4S_TensorboardTests),
    ]
}
#endif
