// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: tensorflow/core/framework/summary.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

enum Tensorflow_DataClass: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int

  /// Unknown data class, used (implicitly) for legacy data. Will not be
  /// processed by data ingestion pipelines.
  case unknown // = 0

  /// Scalar time series. Each `Value` for the corresponding tag must have
  /// `tensor` set to a rank-0 tensor of type `DT_FLOAT` (float32).
  case scalar // = 1

  /// Tensor time series. Each `Value` for the corresponding tag must have
  /// `tensor` set. The tensor value is arbitrary, but should be small to
  /// accommodate direct storage in database backends: an upper bound of a few
  /// kilobytes is a reasonable rule of thumb.
  case tensor // = 2

  /// Blob sequence time series. Each `Value` for the corresponding tag must
  /// have `tensor` set to a rank-1 tensor of bytestring dtype.
  case blobSequence // = 3
  case UNRECOGNIZED(Int)

  init() {
    self = .unknown
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unknown
    case 1: self = .scalar
    case 2: self = .tensor
    case 3: self = .blobSequence
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .unknown: return 0
    case .scalar: return 1
    case .tensor: return 2
    case .blobSequence: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Tensorflow_DataClass] = [
    .unknown,
    .scalar,
    .tensor,
    .blobSequence,
  ]

}

/// Metadata associated with a series of Summary data
struct Tensorflow_SummaryDescription: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Hint on how plugins should process the data in this series.
  /// Supported values include "scalar", "histogram", "image", "audio"
  var typeHint: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// A SummaryMetadata encapsulates information on which plugins are able to make
/// use of a certain summary value.
struct Tensorflow_SummaryMetadata: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Data that associates a summary with a certain plugin.
  var pluginData: Tensorflow_SummaryMetadata.PluginData {
    get {_pluginData ?? Tensorflow_SummaryMetadata.PluginData()}
    set {_pluginData = newValue}
  }
  /// Returns true if `pluginData` has been explicitly set.
  var hasPluginData: Bool {self._pluginData != nil}
  /// Clears the value of `pluginData`. Subsequent reads from it will return its default value.
  mutating func clearPluginData() {self._pluginData = nil}

  /// Display name for viewing in TensorBoard.
  var displayName: String = String()

  /// Longform readable description of the summary sequence. Markdown supported.
  var summaryDescription: String = String()

  /// Class of data stored in this time series. Required for compatibility with
  /// TensorBoard's generic data facilities (`DataProvider`, et al.). This value
  /// imposes constraints on the dtype and shape of the corresponding tensor
  /// values. See `DataClass` docs for details.
  var dataClass: Tensorflow_DataClass = .unknown

  var unknownFields = SwiftProtobuf.UnknownStorage()

  struct PluginData: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// The name of the plugin this data pertains to.
    var pluginName: String = String()

    /// The content to store for the plugin. The best practice is for this to be
    /// a binary serialized protocol buffer.
    var content: Data = Data()

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
  }

  init() {}

  fileprivate var _pluginData: Tensorflow_SummaryMetadata.PluginData? = nil
}

/// A Summary is a set of named values to be displayed by the
/// visualizer.
///
/// Summaries are produced regularly during training, as controlled by
/// the "summary_interval_secs" attribute of the training operation.
/// Summaries are also produced at the end of an evaluation.
struct Tensorflow_Summary: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Set of values for the summary.
  var value: [Tensorflow_Summary.Value] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  struct Image: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// Dimensions of the image.
    var height: Int32 = 0

    var width: Int32 = 0

    /// Valid colorspace values are
    ///   1 - grayscale
    ///   2 - grayscale + alpha
    ///   3 - RGB
    ///   4 - RGBA
    ///   5 - DIGITAL_YUV
    ///   6 - BGRA
    var colorspace: Int32 = 0

    /// Image data in encoded format.  All image formats supported by
    /// image_codec::CoderUtil can be stored here.
    var encodedImageString: Data = Data()

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
  }

  struct Audio: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// Sample rate of the audio in Hz.
    var sampleRate: Float = 0

    /// Number of channels of audio.
    var numChannels: Int64 = 0

    /// Length of the audio in frames (samples per channel).
    var lengthFrames: Int64 = 0

    /// Encoded audio data and its associated RFC 2045 content type (e.g.
    /// "audio/wav").
    var encodedAudioString: Data = Data()

    var contentType: String = String()

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
  }

  struct Value: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// This field is deprecated and will not be set.
    var nodeName: String = String()

    /// Tag name for the data. Used by TensorBoard plugins to organize data. Tags
    /// are often organized by scope (which contains slashes to convey
    /// hierarchy). For example: foo/bar/0
    var tag: String = String()

    /// Contains metadata on the summary value such as which plugins may use it.
    /// Take note that many summary values may lack a metadata field. This is
    /// because the FileWriter only keeps a metadata object on the first summary
    /// value with a certain tag for each tag. TensorBoard then remembers which
    /// tags are associated with which plugins. This saves space.
    var metadata: Tensorflow_SummaryMetadata {
      get {_metadata ?? Tensorflow_SummaryMetadata()}
      set {_metadata = newValue}
    }
    /// Returns true if `metadata` has been explicitly set.
    var hasMetadata: Bool {self._metadata != nil}
    /// Clears the value of `metadata`. Subsequent reads from it will return its default value.
    mutating func clearMetadata() {self._metadata = nil}

    /// Value associated with the tag.
    var value: Tensorflow_Summary.Value.OneOf_Value? = nil

    var simpleValue: Float {
      get {
        if case .simpleValue(let v)? = value {return v}
        return 0
      }
      set {value = .simpleValue(newValue)}
    }

    var obsoleteOldStyleHistogram: Data {
      get {
        if case .obsoleteOldStyleHistogram(let v)? = value {return v}
        return Data()
      }
      set {value = .obsoleteOldStyleHistogram(newValue)}
    }

    var image: Tensorflow_Summary.Image {
      get {
        if case .image(let v)? = value {return v}
        return Tensorflow_Summary.Image()
      }
      set {value = .image(newValue)}
    }

    var histo: Tensorflow_HistogramProto {
      get {
        if case .histo(let v)? = value {return v}
        return Tensorflow_HistogramProto()
      }
      set {value = .histo(newValue)}
    }

    var audio: Tensorflow_Summary.Audio {
      get {
        if case .audio(let v)? = value {return v}
        return Tensorflow_Summary.Audio()
      }
      set {value = .audio(newValue)}
    }

    var tensor: Tensorflow_TensorProto {
      get {
        if case .tensor(let v)? = value {return v}
        return Tensorflow_TensorProto()
      }
      set {value = .tensor(newValue)}
    }

    var unknownFields = SwiftProtobuf.UnknownStorage()

    /// Value associated with the tag.
    enum OneOf_Value: Equatable, Sendable {
      case simpleValue(Float)
      case obsoleteOldStyleHistogram(Data)
      case image(Tensorflow_Summary.Image)
      case histo(Tensorflow_HistogramProto)
      case audio(Tensorflow_Summary.Audio)
      case tensor(Tensorflow_TensorProto)

    }

    init() {}

    fileprivate var _metadata: Tensorflow_SummaryMetadata? = nil
  }

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "tensorflow"

extension Tensorflow_DataClass: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0DATA_CLASS_UNKNOWN\0\u{1}DATA_CLASS_SCALAR\0\u{1}DATA_CLASS_TENSOR\0\u{1}DATA_CLASS_BLOB_SEQUENCE\0")
}

extension Tensorflow_SummaryDescription: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SummaryDescription"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}type_hint\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.typeHint) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.typeHint.isEmpty {
      try visitor.visitSingularStringField(value: self.typeHint, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tensorflow_SummaryDescription, rhs: Tensorflow_SummaryDescription) -> Bool {
    if lhs.typeHint != rhs.typeHint {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Tensorflow_SummaryMetadata: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SummaryMetadata"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}plugin_data\0\u{3}display_name\0\u{3}summary_description\0\u{3}data_class\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._pluginData) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.displayName) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.summaryDescription) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self.dataClass) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._pluginData {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.displayName.isEmpty {
      try visitor.visitSingularStringField(value: self.displayName, fieldNumber: 2)
    }
    if !self.summaryDescription.isEmpty {
      try visitor.visitSingularStringField(value: self.summaryDescription, fieldNumber: 3)
    }
    if self.dataClass != .unknown {
      try visitor.visitSingularEnumField(value: self.dataClass, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tensorflow_SummaryMetadata, rhs: Tensorflow_SummaryMetadata) -> Bool {
    if lhs._pluginData != rhs._pluginData {return false}
    if lhs.displayName != rhs.displayName {return false}
    if lhs.summaryDescription != rhs.summaryDescription {return false}
    if lhs.dataClass != rhs.dataClass {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Tensorflow_SummaryMetadata.PluginData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Tensorflow_SummaryMetadata.protoMessageName + ".PluginData"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}plugin_name\0\u{1}content\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.pluginName) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.content) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.pluginName.isEmpty {
      try visitor.visitSingularStringField(value: self.pluginName, fieldNumber: 1)
    }
    if !self.content.isEmpty {
      try visitor.visitSingularBytesField(value: self.content, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tensorflow_SummaryMetadata.PluginData, rhs: Tensorflow_SummaryMetadata.PluginData) -> Bool {
    if lhs.pluginName != rhs.pluginName {return false}
    if lhs.content != rhs.content {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Tensorflow_Summary: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Summary"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}value\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.value) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.value.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.value, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tensorflow_Summary, rhs: Tensorflow_Summary) -> Bool {
    if lhs.value != rhs.value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Tensorflow_Summary.Image: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Tensorflow_Summary.protoMessageName + ".Image"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}height\0\u{1}width\0\u{1}colorspace\0\u{3}encoded_image_string\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.height) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.width) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.colorspace) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.encodedImageString) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.height != 0 {
      try visitor.visitSingularInt32Field(value: self.height, fieldNumber: 1)
    }
    if self.width != 0 {
      try visitor.visitSingularInt32Field(value: self.width, fieldNumber: 2)
    }
    if self.colorspace != 0 {
      try visitor.visitSingularInt32Field(value: self.colorspace, fieldNumber: 3)
    }
    if !self.encodedImageString.isEmpty {
      try visitor.visitSingularBytesField(value: self.encodedImageString, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tensorflow_Summary.Image, rhs: Tensorflow_Summary.Image) -> Bool {
    if lhs.height != rhs.height {return false}
    if lhs.width != rhs.width {return false}
    if lhs.colorspace != rhs.colorspace {return false}
    if lhs.encodedImageString != rhs.encodedImageString {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Tensorflow_Summary.Audio: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Tensorflow_Summary.protoMessageName + ".Audio"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}sample_rate\0\u{3}num_channels\0\u{3}length_frames\0\u{3}encoded_audio_string\0\u{3}content_type\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFloatField(value: &self.sampleRate) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.numChannels) }()
      case 3: try { try decoder.decodeSingularInt64Field(value: &self.lengthFrames) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.encodedAudioString) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.contentType) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.sampleRate.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.sampleRate, fieldNumber: 1)
    }
    if self.numChannels != 0 {
      try visitor.visitSingularInt64Field(value: self.numChannels, fieldNumber: 2)
    }
    if self.lengthFrames != 0 {
      try visitor.visitSingularInt64Field(value: self.lengthFrames, fieldNumber: 3)
    }
    if !self.encodedAudioString.isEmpty {
      try visitor.visitSingularBytesField(value: self.encodedAudioString, fieldNumber: 4)
    }
    if !self.contentType.isEmpty {
      try visitor.visitSingularStringField(value: self.contentType, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tensorflow_Summary.Audio, rhs: Tensorflow_Summary.Audio) -> Bool {
    if lhs.sampleRate != rhs.sampleRate {return false}
    if lhs.numChannels != rhs.numChannels {return false}
    if lhs.lengthFrames != rhs.lengthFrames {return false}
    if lhs.encodedAudioString != rhs.encodedAudioString {return false}
    if lhs.contentType != rhs.contentType {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Tensorflow_Summary.Value: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Tensorflow_Summary.protoMessageName + ".Value"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}tag\0\u{3}simple_value\0\u{3}obsolete_old_style_histogram\0\u{1}image\0\u{1}histo\0\u{1}audio\0\u{3}node_name\0\u{1}tensor\0\u{1}metadata\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.tag) }()
      case 2: try {
        var v: Float?
        try decoder.decodeSingularFloatField(value: &v)
        if let v = v {
          if self.value != nil {try decoder.handleConflictingOneOf()}
          self.value = .simpleValue(v)
        }
      }()
      case 3: try {
        var v: Data?
        try decoder.decodeSingularBytesField(value: &v)
        if let v = v {
          if self.value != nil {try decoder.handleConflictingOneOf()}
          self.value = .obsoleteOldStyleHistogram(v)
        }
      }()
      case 4: try {
        var v: Tensorflow_Summary.Image?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .image(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .image(v)
        }
      }()
      case 5: try {
        var v: Tensorflow_HistogramProto?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .histo(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .histo(v)
        }
      }()
      case 6: try {
        var v: Tensorflow_Summary.Audio?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .audio(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .audio(v)
        }
      }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.nodeName) }()
      case 8: try {
        var v: Tensorflow_TensorProto?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .tensor(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .tensor(v)
        }
      }()
      case 9: try { try decoder.decodeSingularMessageField(value: &self._metadata) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.tag.isEmpty {
      try visitor.visitSingularStringField(value: self.tag, fieldNumber: 1)
    }
    switch self.value {
    case .simpleValue?: try {
      guard case .simpleValue(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularFloatField(value: v, fieldNumber: 2)
    }()
    case .obsoleteOldStyleHistogram?: try {
      guard case .obsoleteOldStyleHistogram(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularBytesField(value: v, fieldNumber: 3)
    }()
    case .image?: try {
      guard case .image(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case .histo?: try {
      guard case .histo(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }()
    case .audio?: try {
      guard case .audio(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    }()
    default: break
    }
    if !self.nodeName.isEmpty {
      try visitor.visitSingularStringField(value: self.nodeName, fieldNumber: 7)
    }
    try { if case .tensor(let v)? = self.value {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    } }()
    try { if let v = self._metadata {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tensorflow_Summary.Value, rhs: Tensorflow_Summary.Value) -> Bool {
    if lhs.nodeName != rhs.nodeName {return false}
    if lhs.tag != rhs.tag {return false}
    if lhs._metadata != rhs._metadata {return false}
    if lhs.value != rhs.value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
