// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: tensorflow/core/framework/types.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// (== suppress_warning documentation-presence ==)
/// LINT.IfChange
enum Tensorflow_DataType: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int

  /// Not a legal value for DataType.  Used to indicate a DataType field
  /// has not been set.
  case dtInvalid // = 0

  /// Data types that all computation devices are expected to be
  /// capable to support.
  case dtFloat // = 1
  case dtDouble // = 2
  case dtInt32 // = 3
  case dtUint8 // = 4
  case dtInt16 // = 5
  case dtInt8 // = 6
  case dtString // = 7

  /// Single-precision complex
  case dtComplex64 // = 8
  case dtInt64 // = 9
  case dtBool // = 10

  /// Quantized int8
  case dtQint8 // = 11

  /// Quantized uint8
  case dtQuint8 // = 12

  /// Quantized int32
  case dtQint32 // = 13

  /// Float32 truncated to 16 bits.
  case dtBfloat16 // = 14

  /// Quantized int16
  case dtQint16 // = 15

  /// Quantized uint16
  case dtQuint16 // = 16
  case dtUint16 // = 17

  /// Double-precision complex
  case dtComplex128 // = 18
  case dtHalf // = 19
  case dtResource // = 20

  /// Arbitrary C++ data types
  case dtVariant // = 21
  case dtUint32 // = 22
  case dtUint64 // = 23

  /// 5 exponent bits, 2 mantissa bits.
  case dtFloat8E5M2 // = 24

  /// 4 exponent bits, 3 mantissa bits, finite-only, with
  case dtFloat8E4M3Fn // = 25

  /// 2 NaNs (0bS1111111).
  case dtFloat8E4M3Fnuz // = 26

  /// with NaN.
  case dtFloat8E4M3B11Fnuz // = 27

  /// bias, finite-only, with NaNs.
  case dtFloat8E5M2Fnuz // = 28

  /// with NaN.
  case dtInt4 // = 29
  case dtUint4 // = 30
  case dtInt2 // = 31
  case dtUint2 // = 32

  /// 2 exponent bits, 1 mantissa bit, finite-only
  case dtFloat4E2M1Fn // = 33

  /// Do not use!  These are only for TF1's obsolete reference Variables.
  /// Every enum above should have a corresponding value below (verified by
  /// types_test).
  case dtFloatRef // = 101
  case dtDoubleRef // = 102
  case dtInt32Ref // = 103
  case dtUint8Ref // = 104
  case dtInt16Ref // = 105
  case dtInt8Ref // = 106
  case dtStringRef // = 107
  case dtComplex64Ref // = 108
  case dtInt64Ref // = 109
  case dtBoolRef // = 110
  case dtQint8Ref // = 111
  case dtQuint8Ref // = 112
  case dtQint32Ref // = 113
  case dtBfloat16Ref // = 114
  case dtQint16Ref // = 115
  case dtQuint16Ref // = 116
  case dtUint16Ref // = 117
  case dtComplex128Ref // = 118
  case dtHalfRef // = 119
  case dtResourceRef // = 120
  case dtVariantRef // = 121
  case dtUint32Ref // = 122
  case dtUint64Ref // = 123
  case dtFloat8E5M2Ref // = 124
  case dtFloat8E4M3FnRef // = 125
  case dtFloat8E4M3FnuzRef // = 126
  case dtFloat8E4M3B11FnuzRef // = 127
  case dtFloat8E5M2FnuzRef // = 128
  case dtInt4Ref // = 129
  case dtUint4Ref // = 130
  case dtInt2Ref // = 131
  case dtUint2Ref // = 132
  case dtFloat4E2M1FnRef // = 133
  case UNRECOGNIZED(Int)

  init() {
    self = .dtInvalid
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .dtInvalid
    case 1: self = .dtFloat
    case 2: self = .dtDouble
    case 3: self = .dtInt32
    case 4: self = .dtUint8
    case 5: self = .dtInt16
    case 6: self = .dtInt8
    case 7: self = .dtString
    case 8: self = .dtComplex64
    case 9: self = .dtInt64
    case 10: self = .dtBool
    case 11: self = .dtQint8
    case 12: self = .dtQuint8
    case 13: self = .dtQint32
    case 14: self = .dtBfloat16
    case 15: self = .dtQint16
    case 16: self = .dtQuint16
    case 17: self = .dtUint16
    case 18: self = .dtComplex128
    case 19: self = .dtHalf
    case 20: self = .dtResource
    case 21: self = .dtVariant
    case 22: self = .dtUint32
    case 23: self = .dtUint64
    case 24: self = .dtFloat8E5M2
    case 25: self = .dtFloat8E4M3Fn
    case 26: self = .dtFloat8E4M3Fnuz
    case 27: self = .dtFloat8E4M3B11Fnuz
    case 28: self = .dtFloat8E5M2Fnuz
    case 29: self = .dtInt4
    case 30: self = .dtUint4
    case 31: self = .dtInt2
    case 32: self = .dtUint2
    case 33: self = .dtFloat4E2M1Fn
    case 101: self = .dtFloatRef
    case 102: self = .dtDoubleRef
    case 103: self = .dtInt32Ref
    case 104: self = .dtUint8Ref
    case 105: self = .dtInt16Ref
    case 106: self = .dtInt8Ref
    case 107: self = .dtStringRef
    case 108: self = .dtComplex64Ref
    case 109: self = .dtInt64Ref
    case 110: self = .dtBoolRef
    case 111: self = .dtQint8Ref
    case 112: self = .dtQuint8Ref
    case 113: self = .dtQint32Ref
    case 114: self = .dtBfloat16Ref
    case 115: self = .dtQint16Ref
    case 116: self = .dtQuint16Ref
    case 117: self = .dtUint16Ref
    case 118: self = .dtComplex128Ref
    case 119: self = .dtHalfRef
    case 120: self = .dtResourceRef
    case 121: self = .dtVariantRef
    case 122: self = .dtUint32Ref
    case 123: self = .dtUint64Ref
    case 124: self = .dtFloat8E5M2Ref
    case 125: self = .dtFloat8E4M3FnRef
    case 126: self = .dtFloat8E4M3FnuzRef
    case 127: self = .dtFloat8E4M3B11FnuzRef
    case 128: self = .dtFloat8E5M2FnuzRef
    case 129: self = .dtInt4Ref
    case 130: self = .dtUint4Ref
    case 131: self = .dtInt2Ref
    case 132: self = .dtUint2Ref
    case 133: self = .dtFloat4E2M1FnRef
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .dtInvalid: return 0
    case .dtFloat: return 1
    case .dtDouble: return 2
    case .dtInt32: return 3
    case .dtUint8: return 4
    case .dtInt16: return 5
    case .dtInt8: return 6
    case .dtString: return 7
    case .dtComplex64: return 8
    case .dtInt64: return 9
    case .dtBool: return 10
    case .dtQint8: return 11
    case .dtQuint8: return 12
    case .dtQint32: return 13
    case .dtBfloat16: return 14
    case .dtQint16: return 15
    case .dtQuint16: return 16
    case .dtUint16: return 17
    case .dtComplex128: return 18
    case .dtHalf: return 19
    case .dtResource: return 20
    case .dtVariant: return 21
    case .dtUint32: return 22
    case .dtUint64: return 23
    case .dtFloat8E5M2: return 24
    case .dtFloat8E4M3Fn: return 25
    case .dtFloat8E4M3Fnuz: return 26
    case .dtFloat8E4M3B11Fnuz: return 27
    case .dtFloat8E5M2Fnuz: return 28
    case .dtInt4: return 29
    case .dtUint4: return 30
    case .dtInt2: return 31
    case .dtUint2: return 32
    case .dtFloat4E2M1Fn: return 33
    case .dtFloatRef: return 101
    case .dtDoubleRef: return 102
    case .dtInt32Ref: return 103
    case .dtUint8Ref: return 104
    case .dtInt16Ref: return 105
    case .dtInt8Ref: return 106
    case .dtStringRef: return 107
    case .dtComplex64Ref: return 108
    case .dtInt64Ref: return 109
    case .dtBoolRef: return 110
    case .dtQint8Ref: return 111
    case .dtQuint8Ref: return 112
    case .dtQint32Ref: return 113
    case .dtBfloat16Ref: return 114
    case .dtQint16Ref: return 115
    case .dtQuint16Ref: return 116
    case .dtUint16Ref: return 117
    case .dtComplex128Ref: return 118
    case .dtHalfRef: return 119
    case .dtResourceRef: return 120
    case .dtVariantRef: return 121
    case .dtUint32Ref: return 122
    case .dtUint64Ref: return 123
    case .dtFloat8E5M2Ref: return 124
    case .dtFloat8E4M3FnRef: return 125
    case .dtFloat8E4M3FnuzRef: return 126
    case .dtFloat8E4M3B11FnuzRef: return 127
    case .dtFloat8E5M2FnuzRef: return 128
    case .dtInt4Ref: return 129
    case .dtUint4Ref: return 130
    case .dtInt2Ref: return 131
    case .dtUint2Ref: return 132
    case .dtFloat4E2M1FnRef: return 133
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Tensorflow_DataType] = [
    .dtInvalid,
    .dtFloat,
    .dtDouble,
    .dtInt32,
    .dtUint8,
    .dtInt16,
    .dtInt8,
    .dtString,
    .dtComplex64,
    .dtInt64,
    .dtBool,
    .dtQint8,
    .dtQuint8,
    .dtQint32,
    .dtBfloat16,
    .dtQint16,
    .dtQuint16,
    .dtUint16,
    .dtComplex128,
    .dtHalf,
    .dtResource,
    .dtVariant,
    .dtUint32,
    .dtUint64,
    .dtFloat8E5M2,
    .dtFloat8E4M3Fn,
    .dtFloat8E4M3Fnuz,
    .dtFloat8E4M3B11Fnuz,
    .dtFloat8E5M2Fnuz,
    .dtInt4,
    .dtUint4,
    .dtInt2,
    .dtUint2,
    .dtFloat4E2M1Fn,
    .dtFloatRef,
    .dtDoubleRef,
    .dtInt32Ref,
    .dtUint8Ref,
    .dtInt16Ref,
    .dtInt8Ref,
    .dtStringRef,
    .dtComplex64Ref,
    .dtInt64Ref,
    .dtBoolRef,
    .dtQint8Ref,
    .dtQuint8Ref,
    .dtQint32Ref,
    .dtBfloat16Ref,
    .dtQint16Ref,
    .dtQuint16Ref,
    .dtUint16Ref,
    .dtComplex128Ref,
    .dtHalfRef,
    .dtResourceRef,
    .dtVariantRef,
    .dtUint32Ref,
    .dtUint64Ref,
    .dtFloat8E5M2Ref,
    .dtFloat8E4M3FnRef,
    .dtFloat8E4M3FnuzRef,
    .dtFloat8E4M3B11FnuzRef,
    .dtFloat8E5M2FnuzRef,
    .dtInt4Ref,
    .dtUint4Ref,
    .dtInt2Ref,
    .dtUint2Ref,
    .dtFloat4E2M1FnRef,
  ]

}

/// Represents a serialized tf.dtypes.Dtype
struct Tensorflow_SerializedDType: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var datatype: Tensorflow_DataType = .dtInvalid

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "tensorflow"

extension Tensorflow_DataType: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0DT_INVALID\0\u{1}DT_FLOAT\0\u{1}DT_DOUBLE\0\u{1}DT_INT32\0\u{1}DT_UINT8\0\u{1}DT_INT16\0\u{1}DT_INT8\0\u{1}DT_STRING\0\u{1}DT_COMPLEX64\0\u{1}DT_INT64\0\u{1}DT_BOOL\0\u{1}DT_QINT8\0\u{1}DT_QUINT8\0\u{1}DT_QINT32\0\u{1}DT_BFLOAT16\0\u{1}DT_QINT16\0\u{1}DT_QUINT16\0\u{1}DT_UINT16\0\u{1}DT_COMPLEX128\0\u{1}DT_HALF\0\u{1}DT_RESOURCE\0\u{1}DT_VARIANT\0\u{1}DT_UINT32\0\u{1}DT_UINT64\0\u{1}DT_FLOAT8_E5M2\0\u{1}DT_FLOAT8_E4M3FN\0\u{1}DT_FLOAT8_E4M3FNUZ\0\u{1}DT_FLOAT8_E4M3B11FNUZ\0\u{1}DT_FLOAT8_E5M2FNUZ\0\u{1}DT_INT4\0\u{1}DT_UINT4\0\u{1}DT_INT2\0\u{1}DT_UINT2\0\u{1}DT_FLOAT4_E2M1FN\0\u{2}D\u{1}DT_FLOAT_REF\0\u{1}DT_DOUBLE_REF\0\u{1}DT_INT32_REF\0\u{1}DT_UINT8_REF\0\u{1}DT_INT16_REF\0\u{1}DT_INT8_REF\0\u{1}DT_STRING_REF\0\u{1}DT_COMPLEX64_REF\0\u{1}DT_INT64_REF\0\u{1}DT_BOOL_REF\0\u{1}DT_QINT8_REF\0\u{1}DT_QUINT8_REF\0\u{1}DT_QINT32_REF\0\u{1}DT_BFLOAT16_REF\0\u{1}DT_QINT16_REF\0\u{1}DT_QUINT16_REF\0\u{1}DT_UINT16_REF\0\u{1}DT_COMPLEX128_REF\0\u{1}DT_HALF_REF\0\u{1}DT_RESOURCE_REF\0\u{1}DT_VARIANT_REF\0\u{1}DT_UINT32_REF\0\u{1}DT_UINT64_REF\0\u{1}DT_FLOAT8_E5M2_REF\0\u{1}DT_FLOAT8_E4M3FN_REF\0\u{1}DT_FLOAT8_E4M3FNUZ_REF\0\u{1}DT_FLOAT8_E4M3B11FNUZ_REF\0\u{1}DT_FLOAT8_E5M2FNUZ_REF\0\u{1}DT_INT4_REF\0\u{1}DT_UINT4_REF\0\u{1}DT_INT2_REF\0\u{1}DT_UINT2_REF\0\u{1}DT_FLOAT4_E2M1FN_REF\0")
}

extension Tensorflow_SerializedDType: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SerializedDType"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}datatype\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.datatype) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.datatype != .dtInvalid {
      try visitor.visitSingularEnumField(value: self.datatype, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tensorflow_SerializedDType, rhs: Tensorflow_SerializedDType) -> Bool {
    if lhs.datatype != rhs.datatype {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
